### ISSUE TITLE
Create the Welcome/ Login Screen for Library app

### ISSUE THREAD

**Issue by risbah** [MartynasVq/LibraryProject#4]
Use you best judgement for how this will be done

Suggestion: 
- make menu system
- prompt for username/ password
- keep prompting for input until user quits or enters correct credentials
- assume we are not using DB and there is a hashmap of username:password (if this causes problems, then idk i guess we have to wait for DB)

**Comment by SuperALKALINEdroiD** [comment]
can we do it html/css

**Comment by risbah** [comment]
Closed with `loginController
